"""File service – handles .uml / .umlproj file operations and markdown export."""

import json
import logging
import os
from datetime import datetime
from app.models.uml import UmlDiagram, Project, create_default_project
from app.core.config import get_settings

settings = get_settings()
logger = logging.getLogger(__name__)


def ensure_dirs():
    os.makedirs(settings.uml_dir, exist_ok=True)


def save_diagram(diagram: UmlDiagram, filepath: str | None = None) -> str:
    """Save a UML diagram to a .uml JSON file. Returns the filepath."""
    ensure_dirs()
    if not filepath:
        filepath = os.path.join(
            settings.uml_dir,
            f"{diagram.name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.uml",
        )
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(diagram.model_dump(), f, indent=2, ensure_ascii=False)
    return filepath


def load_diagram(filepath: str) -> UmlDiagram:
    """Load a UML diagram from a .uml JSON file.

    Also handles project-format data (``diagrams`` key) by extracting the
    first diagram — this can happen when a ``.umlproj`` file was renamed to
    ``.uml`` or when ``save-project`` wrote to a ``.uml`` path.
    """
    ensure_dirs()
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    # Project-format data → extract the active diagram
    if "diagrams" in data:
        diagrams = data.get("diagrams", [])
        if diagrams:
            active_idx = data.get("active_diagram_index", 0)
            if 0 <= active_idx < len(diagrams):
                logger.info(
                    f"[FileService] Extracted diagram {active_idx} "
                    f"from project-format file: {os.path.basename(filepath)}"
                )
                return UmlDiagram(**diagrams[active_idx])
            return UmlDiagram(**diagrams[0])
    return UmlDiagram(**data)


def list_diagrams() -> list[dict]:
    """List all saved UML diagrams."""
    ensure_dirs()
    files = []
    if os.path.exists(settings.uml_dir):
        for fname in os.listdir(settings.uml_dir):
            if fname.endswith(".uml"):
                fpath = os.path.join(settings.uml_dir, fname)
                stat = os.stat(fpath)
                files.append({
                    "name": fname,
                    "path": fpath,
                    "size": stat.st_size,
                    "modified": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                })
    return sorted(files, key=lambda f: f["modified"], reverse=True)


def export_markdown(diagram: UmlDiagram) -> str:
    """Export a UML diagram as a Markdown design document."""

    def vis_symbol(v: str) -> str:
        return {"+": "+", "-": "-", "#": "#"}.get(v, v)

    lines = [
        f"# {diagram.name} – UML Design Document",
        "",
        f"> Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
        "## Class Overview",
        "",
    ]

    for c in diagram.classes:
        stereotype_tag = f"«{c.stereotype}»" if c.stereotype != "class" else ""
        title = f"{stereotype_tag} **{c.name}**" if stereotype_tag else f"**{c.name}**"
        lines.append(f"### {title}")
        lines.append("")

        if c.note:
            lines.append(f"> {c.note}")
            lines.append("")

        lines.append("| Visibility | Name | Type / Return | Params |")
        lines.append("|-----------|------|---------------|--------|")

        for a in c.attributes:
            lines.append(f"| `{a.visibility}` | {a.name} | {a.type} | |")

        for m in c.methods:
            lines.append(f"| `{m.visibility}` | {m.name}() | {m.return_type} | {m.params} |")

        lines.append("")

    # Relations
    if diagram.relations:
        lines.append("---")
        lines.append("")
        lines.append("## Relations")
        lines.append("")

        for r in diagram.relations:
            src_name = next(
                (c.name for c in diagram.classes if c.id == r.source), r.source
            )
            tgt_name = next(
                (c.name for c in diagram.classes if c.id == r.target), r.target
            )
            rel_line = f"- **{src_name}** → **{tgt_name}**: `{r.type}`"
            if r.multiplicity_source or r.multiplicity_target:
                rel_line += f" [{r.multiplicity_source}..{r.multiplicity_target}]"
            if r.role_name:
                rel_line += f" role: `{r.role_name}`"
            lines.append(rel_line)
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by UML Designer*")

    return "\n".join(lines)


# ── Project file operations (.umlproj) ──────────────────


def save_project(project: Project, filepath: str | None = None) -> str:
    """Save a Project to a .umlproj JSON file. Returns the filepath."""
    ensure_dirs()
    if not filepath:
        filepath = os.path.join(
            settings.uml_dir,
            f"{project.name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.umlproj",
        )
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(project.model_dump(), f, indent=2, ensure_ascii=False)
    logger.info(f"[Project] Saved project '{project.name}' ({len(project.diagrams)} diagrams) → {filepath}")
    return filepath


def load_project(filepath: str) -> Project:
    """Load a Project from a .umlproj JSON file.

    Also handles legacy .uml files by wrapping them in a Project container.
    """
    ensure_dirs()
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Check if this is a Project or a legacy single diagram
    if "diagrams" in data:
        project = Project(**data)
        logger.info(f"[Project] Loaded project '{project.name}' ({len(project.diagrams)} diagrams) from {filepath}")
        return project

    # Legacy .uml file — wrap in a Project
    diagram = UmlDiagram(**data)
    project = Project(
        name=diagram.name,
        diagrams=[diagram],
        active_diagram_index=0,
    )
    logger.info(f"[Project] Wrapped legacy .uml diagram '{diagram.name}' in project from {filepath}")
    return project


def list_projects() -> list[dict]:
    """List all saved Projects (.umlproj files)."""
    ensure_dirs()
    files = []
    if os.path.exists(settings.uml_dir):
        for fname in os.listdir(settings.uml_dir):
            if fname.endswith(".umlproj"):
                fpath = os.path.join(settings.uml_dir, fname)
                stat = os.stat(fpath)
                files.append({
                    "name": fname,
                    "path": fpath,
                    "size": stat.st_size,
                    "modified": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                })
    logger.debug(f"[Project] Listed {len(files)} .umlproj projects")
    return sorted(files, key=lambda f: f["modified"], reverse=True)
